config/routes.rb
Songbook::Application.routes.draw do
  
  resources :favorites

  resources :chords

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :songs

  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => :show
  
  
  match 'converter' => 'converter#index', :as => :translation
  match '/fav/:song_id' => 'favorites#fav' 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  after_create { |admin| admin.send_reset_password_instructions }
  
  def password_required?
    new_record? ? false : super
  end
end

app/models/chord.rb
class Chord < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user_id
  belongs_to :song_id
end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/models/translation.rb
class Translation
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

    attr_accessor :name, :email, :content

    validates_presence_of :name
    validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
    validates_length_of :content, :maximum => 500

    def initialize(attributes = {})
      attributes.each do |name, value|
        send("#{name}=", value)
      end
    end

    def persisted?
      false
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  has_many :favorites
  
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    else # Create a user with a stub password. 
      User.create!(:email => data.email, :password => Devise.friendly_token[0,20], :name => data.name) 
    end
  end
  
  def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"]
        end
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chords_controller.rb
class ChordsController < InheritedResources::Base
end

app/controllers/converter_controller.rb
class ConverterController < ApplicationController
  def index

    if params[:commit] == "Submeter" 
      @song = Song.new
      @song.title = params[:title]
      @song.number = params[:number]
      @song.lyrics = params[:lyrics]
      @song.author = params[:author]
      @song.save

      respond_to do |format|
        if @song.save
          format.html { redirect_to @song, notice: 'Song was successfully submited.' }
          format.json { render json: @song, status: :created, location: @song }
        end
      end

    else
      if params[:contents]
        value = params[:contents]
        value = value.gsub!(/\\beginverse\s*(% start verse)*/, '<div class="verse">')
        value = value.gsub!(/\\endverse\s*(% end verse)*/, "</div>")
        
        value = value.gsub!(/\\beginchorus\s*(% start chorus)*/, '<div class="chorus">')
        value = value.gsub!(/\\endchorus\s*(% end chorus)*/, "</div>")
        value = value.gsub!(/\\[\[]([a-z0-9#]*)[\]]/i, '<span class="chord \1">\1</span>')

        value = value.gsub!(/^(?=.*?%).*$/, "")
        value = value.gsub!(/\n{2,}/, '')
        value = value.gsub!(/(^(?!.*div*).*)$/, '<p>\1</p>')
        value = value.gsub!(/<p>[\s$]*<\/p>/, '')
        value = value.gsub!(/\s*\r/,'')
        value = value.gsub!(/\n\r/, "\r")

      end
    end
    
    @translation = Translation.new
  end
  
  def create
    @translation = Translation.new(params[:contents])

    respond_to do |format|
      if @translation.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def fav
    favorite = Favorite.find_or_initialize_by_user_id_and_song_id(current_user.id, params[:song_id])
    favorite.update_attributes({
      :user_id => current_user.id,
      :song_id => params[:song_id]
    })
    redirect_to(song_path(params[:song_id]))
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all(:order => "number ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/helpers/converter_helper.rb
module ConverterHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chords/_form.html.erb
<%= form_for(@chord) do |f| %>
  <% if @chord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chord.errors.count, "error") %> prohibited this chord from being saved:</h2>

      <ul>
      <% @chord.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chords/edit.html.erb
<h1>Editing chord</h1>

<%= render 'form' %>

<%= link_to 'Show', @chord %> |
<%= link_to 'Back', chords_path %>

app/views/chords/index.html.erb
<h1>Listing chords</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chords.each do |chord| %>
  <tr>
    <td><%= chord.name %></td>
    <td><%= link_to 'Show', chord %></td>
    <td><%= link_to 'Edit', edit_chord_path(chord) %></td>
    <td><%= link_to 'Destroy', chord, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chord', new_chord_path %>

app/views/chords/new.html.erb
<h1>New chord</h1>

<%= render 'form' %>

<%= link_to 'Back', chords_path %>

app/views/chords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chord.name %>
</p>


<%= link_to 'Edit', edit_chord_path(@chord) %> |
<%= link_to 'Back', chords_path %>

app/views/converter/index.html.erb
<div class="page-title">
	<h1>Leitor LaTeX</h1>
</div>
<div class="row">
	<div class="span6">
		<h2>HTML</h2>
		<div class="translation well lyrics">
			<% if params[:contents] != nil %>
			<%= params[:contents].html_safe %>
			<% end %>
		</div>
	</div>

	<div class="span4 offset1">


	<%= form_tag 'converter', :class => "form-horizotanl" do |f| %>
	<% if params[:contents] %>
		<h2>Detalhes</h2>
		<label for="title">Título</label><input type="text" name="title" id="title"/>
		<label for="number">Número</label><input type="text" name="number" id="number"/>
		<label for="author">Autor</label><input type="text" name="author" id="author"/>
		<textarea name="lyrics" style="display:none">
		 		<% if params[:contents] != nil %>
				<%= params[:contents].html_safe %>
				<% end %>
		</textarea>
		<div class="form-actions">
			<%= submit_tag 'Submeter', :name => "commit" %>
		</div>

	<% else %>
		<h2>LaTeX</h2>
		<textarea name="contents" name="contents" class="span4" rows="10"></textarea>
		<div class="form-actions">
			<%= submit_tag 'Previsualizar', :name => "commit" %>
			<%= submit_tag 'Submeter', :name => "commit" %>
		</div>
	<% end %>
	</div>
</div>
<% end %>

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :song_id %><br />
    <%= f.text_field :song_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Listing favorites</h1>

<table>
  <tr>
    <th>User</th>
    <th>Song</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.user_id %></td>
    <td><%= favorite.song_id %></td>
    <td><%= link_to 'Show', favorite %></td>
    <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
    <td><%= link_to 'Destroy', favorite, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @favorite.user_id %>
</p>

<p>
  <b>Song:</b>
  <%= @favorite.song_id %>
</p>


<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/home/index.html.erb
<div class="hero-unit">
	<h1>Um novo psaltério</h1>
	<p>Este sou eu, de cara lavada!.</p>
	<p><a class="btn btn-primary btn-large">Ler mais »</a></p>
</div>

<div class="row">
        <div class="span4">
          <h2>Mais música</h2>
           <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#"><i class="icon-headphones"></i> Ler mais »</a></p>
        </div>
        <div class="span4">
          <h2>Mais social</h2>
           <p>Partilha a tua música preferida no facebook ou twitter! Sabias que podes contribuir para o psaltério? Além de ser um sistema gratuito, o seu código está disponível na internet!</p>
          <p><a class="btn" href="#"><i class="icon-comment"></i> Ler mais »</a></p>
       </div>
        <div class="span4">
          <h2>Mais moderno</h2>
          <p>Ao redesenhar o website do psaltério utilizámos muitas das mais recentes tecnologias. Tudo para que o teu psaltério funcione melhor, e seja mais agradável!</p>
          <p><a class="btn" href="#"><i class="icon-chevron-right"></i> Ler mais »</a></p>
        </div>
</div>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :lyrics %><br />
    <%= f.text_area :lyrics %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br />
    <%= f.check_box :enabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<div class="page-title">
	<h1>Músicas</h1>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>Título</th>
		</tr>
	</thead>
<% @songs.each do |song| %>
<tr>
	<td><%= song.number %></td>
	<td><%= link_to song.title, song %></td>
</tr>
<% end %>
</table>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<div class="page-title">
	<h1> <%= @song.title %>	<small><%= @song.number %></small></h1>
	<h4>Letra e música por <%= @song.author %></h4>
	<small><%= link_to "+ Favorite", "/fav/#{@song.id}", :class => "btn default"%></small>
</div>

<div class="row-fluid">
	<div class="span12">
		<div class="well">
			<div class="lyrics">
			  <%= @song.lyrics.html_safe %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>